#--------------------------------------------------------------
# Secret
# https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
# 作成コマンド
# $ htpasswd -c auth {user name}
# $ kubectl create secret generic basic-auth --from-file=auth
# $ kubectl get secret basic-auth -o yaml
# $ kubectl delete secret basic-auth
#--------------------------------------------------------------
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth
data:
  auth: Zm9vOiRhcHIxJGw1T3BwYzdVJG1hL2h5V3Z3ekhIbkJOTHBqZmF5Ri4K
