---
#--------------------------------------------------------------
# Deployment for minio
# https://kubernetes.io/ja/docs/concepts/workloads/controllers/deployment/
#--------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
spec:
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app: s3
    spec:
      # 削除されるまでの猶予の時間。デフォルトは30秒
      terminationGracePeriodSeconds: 60
      containers:
        # https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html
        - image: minio/minio:RELEASE.2022-10-24T18-35-07Z
          name: s3
          command: ["/bin/sh", "-c"]
          args:
            [
              "mkdir -p /data/bucket; /usr/bin/docker-entrypoint.sh server /data --console-address ':9001'",
            ]
          ports:
            - containerPort: 9000
              name: s3-api
            - containerPort: 9001
              name: s3-dashboard
          env:
            - name: MINIO_ROOT_USER
              value: minioroot
            - name: MINIO_ROOT_PASSWORD
              value: minioroot
          volumeMounts:
            - name: data-s3
              mountPath: /data
      volumes:
        - name: data-s3
          hostPath:
            path: "/data/s3"
