---
#--------------------------------------------------------------
# HorizontalPodAutoscaler
#--------------------------------------------------------------
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: s3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: s3
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
