---
#--------------------------------------------------------------
# Service for postgres
# https://kubernetes.io/ja/docs/concepts/services-networking/service/
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
