apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#--------------------------------------------------
# Change value
#--------------------------------------------------
namePrefix: hello-
commonLabels:
  app: cronjob
  env: dev
images:
  - name: alpine
    newName: alpine
    newTag: 3.15.1
#--------------------------------------------------
# Base
#--------------------------------------------------
bases:
  - ../../../base/cronjob
resources:
  - namespace.yaml
patchesJson6902:
- target:
    group: ""
    version: v1
    kind: Namespace
    name: cronjob
  path: patch-namespace.yaml
- target:
    group: batch
    version: v1beta1
    kind: CronJob
    name: cronjob
  path: patch-cronjob.yaml
