apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: kustomize-templates
deploy:
  kustomize:
    paths:
    # for ArgoCD
    # - kustomize/overlays/dev/argocd
    # examples
    # - kustomize/overlays/dev/nginx1
    # - kustomize/overlays/dev/nginx2
    #--------------------------------------------------
    # local
    #--------------------------------------------------
    - kustomize/overlays/local/namespace
    # for ArgoCD
    # - kustomize/overlays/local/argocd
    # - kustomize/overlays/local/traefik-nginx1
    # - kustomize/overlays/local/traefik-argocd   # argocd:   http://argocd-server.local:8081/ admin/****
    # - kustomize/overlays/local/db/mysql         # mysql:    localhost:30306 root/rootpass
    # - kustomize/overlays/local/db/postgres      # postgres: localhost:30432 admin/rootpass
    # - kustomize/overlays/local/aws/s3           # minio:    http://localhost:30101
    - kustomize/overlays/local/redis            # redis:    http://localhost:30379
    # - kustomize/overlays/local/volume
