apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: kustomize-templates
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
    concurrency: 0
    useBuildkit: true
  artifacts:
    - image: main
      context: .
      docker:
        dockerfile: ./docker/Dockerfile
profiles:
- name: namespace
  deploy:
    kustomize:
      paths: 
        - kustomize/overlays/local/namespace
        - kustomize/overlays/common/namespace-istio-ingress
- name: local-infra
  deploy:
    kustomize:
      defaultNamespace: infra-local
      paths: 
        - kustomize/overlays/local/db/mysql         # mysql:    localhost:30306 root/rootpass
        - kustomize/overlays/local/db/postgres      # postgres: localhost:30432 admin/rootpass
        - kustomize/overlays/local/aws/s3           # minio:    http://localhost:30101
        # - kustomize/overlays/local/redis            # redis:    http://localhost:30379
        # - kustomize/overlays/local/volume
#--------------------------------------------------
# local: App
#--------------------------------------------------
- name: local-app
  deploy:
    kustomize:
      defaultNamespace: app
      paths: 
          - kustomize/overlays/local/test-app       # http://test-app.local:8081/
          # - kustomize/overlays/local/ingress-nginx1
          # - kustomize/overlays/local/ingress-nginx1
          # - kustomize/overlays/dev/nginx1
#--------------------------------------------------
# dev: App
#--------------------------------------------------
- name: dev-app
  deploy:
    kustomize:
      defaultNamespace: app
      paths: 
          - kustomize/overlays/dev/test-app
- name: infra
  deploy:
    helm:
      releases:
        # redis
        - name: redis
          namespace: infra
          createNamespace: true
          repo: https://charts.bitnami.com/bitnami
          remoteChart: redis
#--------------------------------------------------
# local: ArgoCD
# https://argo-cd.readthedocs.io/en/stable/
#--------------------------------------------------
- name: local-argocd
  deploy:
    kustomize:
      defaultNamespace: argocd
      paths: 
        - kustomize/overlays/common/namespace-argocd
        - kustomize/overlays/local/argocd
        # argocd:   http://argocd-server.local:8081/ admin/****
        - kustomize/overlays/local/ingress-argocd
#--------------------------------------------------
# local: kube-prometheus-stack
# https://github.com/prometheus-operator/kube-prometheus
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
#--------------------------------------------------
- name: local-monitoring
  deploy:
    helm:
      releases:
        - name: kube-prometheus-stack
          namespace: monitoring
          createNamespace: true
          repo: https://prometheus-community.github.io/helm-charts
          remoteChart: kube-prometheus-stack
    kustomize:
      defaultNamespace: monitoring
      paths: 
          # prometheus:   http://prometheus-server.local:8081/
          - kustomize/overlays/local/ingress-prometheus
#--------------------------------------------------
# metrics-server
# https://docs.aws.amazon.com/eks/latest/userguide/metrics-server.html
#--------------------------------------------------
- name: metrics-server
  deploy:
    kubectl:
      manifests:
        - "https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml"

#--------------------------------------------------
# for EKS
# https://docs.aws.amazon.com/ja_jp/prescriptive-guidance/latest/containers-provision-eks-clusters-terraform/helm-add-ons.html
# - metrics-server
#   - check metrics-server
#    $ kubectl top nodes
# - ArgoCD
#   - check argocd
#    $ kubectl port-forward svc/argocd-server -n argocd 8081:443
# - kube-prometheus-stack
#   - check prometheus
#    $ kubectl port-forward svc/kube-prometheus-stack-prometheus -n monitoring 9090:9090
# - cluster autoscaler
#--------------------------------------------------
# - name: eks
#   deploy:
#     kubectl:
#       manifests:
#         # metrics-server
#         - "kubectl/aws/metrics-server/components.yaml"
#     helm:
#       hooks:
#         before:
#         - host:
#             command: ["helm","repo","add","aws","https://aws.github.io/eks-charts"]
#             os: [linux]
#       releases:
        # # Cluster Autoscaler
        # # https://artifacthub.io/packages/helm/cluster-autoscaler/cluster-autoscaler
        # - name: cluster-autoscaler
        #   namespace: kube-system
        #   createNamespace: false
        #   repo: https://kubernetes.github.io/autoscaler
        #   remoteChart: cluster-autoscaler
        #   # https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/values.yaml
        #   setValues:
        #     autoDiscovery.clusterName: base-test
        #     awsRegion: ap-northeast-1
        #     image.tag: v1.22.0
        #     rbac.serviceAccount.annotations.eks\.amazonaws\.com/role-arn: arn:aws:iam::xxxxxxxxxxxx:role/base-test-ClusterAutoscalerRole
        #     rbac.serviceAccount.name: cluster-autoscaler
        # Prometheus Stack
        # - name: kube-prometheus-stack
        #   namespace: monitoring
        #   createNamespace: true
        #   repo: https://prometheus-community.github.io/helm-charts
        #   remoteChart: kube-prometheus-stack
        # FluentBit
        # https://artifacthub.io/packages/helm/aws/aws-for-fluent-bit
        # - name: fluent-bit
        #   namespace: kube-system
        #   createNamespace: false
        #   # Note: For some reason, helm install fails with an error when I put in the repo as is.
        #   # repo: https://aws.github.io/eks-charts
        #   remoteChart: aws/aws-for-fluent-bit
        #   version: 0.1.16
        #   setValues:
        #     cloudWatch.enabled: true
        #     cloudWatch.region: ap-northeast-1
        #     cloudWatch.logGroupName: /aws/eks/fluent-bit-cloudwatch/logs
        #     cloudWatch.logRetentionDays: 14
        #     serviceAccount.name: fluent-bit
        #     serviceAccount.annotations.eks\.amazonaws\.com/role-arn: arn:aws:iam::xxxxxxxxxx:role/base-test-FluentBitRole
        #     global.namespaceOverride: kube-system
        #     image.tag: 2.21.5
        #     kinesis.enabled: false
        #     elasticsearch.enabled: false
    # kustomize:
    #   defaultNamespace: argocd
    #   paths: 
    #     - kustomize/overlays/dev/argocd

#--------------------------------------------------
# istio
# https://istio.io/latest/
# https://istio.io/latest/docs/setup/install/helm/
#--------------------------------------------------
- name: istio
  deploy:
    helm:
      releases:
        - name: base
          namespace: istio-system
          createNamespace: true
          repo: https://istio-release.storage.googleapis.com/charts
          remoteChart: base
        - name: istiod
          namespace: istio-system
          repo: https://istio-release.storage.googleapis.com/charts
          remoteChart: istiod
          wait: true

#--------------------------------------------------
# istio-ingress
# https://istio.io/latest/docs/setup/install/helm/
#--------------------------------------------------
- name: istio-ingress
  deploy:
    helm:
      releases:
        - name: gateway
          namespace: istio-ingress
          repo: https://istio-release.storage.googleapis.com/charts
          remoteChart: gateway
