apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: kustomize-templates
deploy:
  kustomize:
    paths:
    - kustomize/overlays/dev/namespace
    # for ArgoCD
    # - kustomize/overlays/dev/argocd
    # - kustomize/overlays/dev/traefik-argocd
    # examples
    # - kustomize/overlays/dev/traefik-nginx1
    # - kustomize/overlays/dev/nginx1
    # - kustomize/overlays/dev/nginx2
    - kustomize/overlays/dev/db/mysql
    # - kustomize/overlays/dev/db/postgres
    - kustomize/overlays/dev/aws/s3
    - kustomize/overlays/dev/volume
