apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#--------------------------------------------------
# Change value
#--------------------------------------------------
commonLabels:
  app: external_dns
  env: dev
images:
  - name: alpine
    newName: alpine
    newTag: 3.15.1
#--------------------------------------------------
# Base
#--------------------------------------------------
bases:
  - ../../../base/aws/external_dns
patchesJson6902:
  - target:
    group: ""
    version: v1
    kind: Deployment
    name: external-dns
  path: patch-deployment.yaml
