---
#--------------------------------------------------------------
# Service for minio
# https://kubernetes.io/ja/docs/concepts/services-networking/service/
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: s3
spec:
  type: NodePort
  selector:
    app: s3
  ports:
    - name: s3-api
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30100
    - name: s3-dashboard
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30101
