apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /favicon.ico {
        access_log off;
        log_not_found off;
      }
      location = /nginx_status {
        stub_status on;
        access_log off;
        log_not_found off;
      }
      location = /apple-app-site-association {
        access_log off;
        log_not_found off;
      }
      location = /.well-known/apple-app-site-association {
        access_log off;
        log_not_found off;
      }
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.spec.tls.hosts.domainPrefix }}.{{ .Values.ingress.spec.tls.hosts.domainRegion | default "japaneast" }}.{{ .Values.ingress.spec.tls.hosts.domain }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.ingress.spec.tls.hosts.domainPrefix }}.{{ .Values.ingress.spec.tls.hosts.domainRegion | default "japaneast" }}.{{ .Values.ingress.spec.tls.hosts.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ include "helmapp.fullname" . }}-proxy-service
          servicePort: 80
        path: /(.*)
  - host: {{ .Values.ingress.spec.rules.host1 }}
    http:
      paths:
      - backend:
          serviceName: {{ include "helmapp.fullname" . }}-proxy-service
          servicePort: 80
        path: /(.*)
  - host: {{ .Values.ingress.spec.rules.host2 }}
    http:
      paths:
      - backend:
          serviceName: {{ include "helmapp.fullname" . }}-proxy-service
          servicePort: 80
        path: /(.*)
