apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /a
            backend:
              serviceName: service
              servicePort: 80
          - path: /b
            backend:
              serviceName: service1
              servicePort: 80
