---
#--------------------------------------------------------------
# Service
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  type: ExternalName
  # {service}.{namespace}.svc.cluster.local
  externalName: nginx1-svc.nginx1-app.svc.cluster.local
  ports:
  - name: http
    port: 80
---
#--------------------------------------------------------------
# Service
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: svc2
spec:
  type: ExternalName
  # {service}.{namespace}.svc.cluster.local
  externalName: nginx2-svc.nginx2-app.svc.cluster.local
  ports:
  - name: http
    port: 80
