apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#--------------------------------------------------
# Change value
#--------------------------------------------------
commonLabels:
  istio-injection: enabled
#--------------------------------------------------
# Base
#--------------------------------------------------
resources:
  - namespace.yaml
