apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#--------------------------------------------------
# Change value
#--------------------------------------------------
commonLabels:
  app: cronjob
  env: production
  project: "test"
images:
  - name: image
    newName: alpine
    newTag: 3.11.5
#--------------------------------------------------
# Base
#--------------------------------------------------
bases:
  - ../../../base/aws/external_dns
patchesJson6902:
  - target:
    group: ""
    version: v1
    kind: Deployment
    name: external-dns
  path: patch-deployment.yaml
