---
#--------------------------------------------------------------
# PersistentVolumeClaim for hostpath
# https://kubernetes.io/ja/docs/concepts/storage/persistent-volumes/
#--------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
