apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#--------------------------------------------------
# Change value
#--------------------------------------------------
namePrefix: base-nginx2-
namespace: base-app
commonLabels:
  app: nginx
  env: production
  project: "test"
images:
  - name: image
    newName: nginx
    newTag: 1.21.6-alpine
#--------------------------------------------------
# Base
#--------------------------------------------------
bases:
  - ../../../base/deployment
patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-service.yaml
