---
#--------------------------------------------------------------
# Service
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  # type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
