apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
# https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource
provisioner: kubernetes.io/no-provisioner
# 実際に紐付けを待つ場合は、WaitForFirstConsumer
# 即時にPVを紐付ける場合、Immediate
volumeBindingMode: WaitForFirstConsumer
