---
#--------------------------------------------------------------
# Service
# https://kubernetes.io/ja/docs/concepts/services-networking/service/
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  type: NodePort
  selector:
    app: redis
    role: master
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
spec:
  type: NodePort
  selector:
    app: redis
    role: slave
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30380
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master-headless
spec:
  type: ClusterIP
  selector:
    app: redis
    role: master
  clusterIP: None
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave-headless
spec:
  type: ClusterIP
  selector:
    app: redis
    role: slave
  clusterIP: None
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
