---
#--------------------------------------------------------------
# Service for mysql
# https://kubernetes.io/ja/docs/concepts/services-networking/service/
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306
