---
#--------------------------------------------------------------
# Deployment
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
#--------------------------------------------------------------
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  # Rolling Update
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 5
  # PodTemplate, もし変更があるとRollingUpdateが開始される
  template:
    spec:
      containers:
        - name: pod
          image: image:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 80
          readinessProbe:
            # an http probe
            httpGet:
              path: /healthcheck
              port: 80
              httpHeaders:
                - name: X-Health-Check
                  value: health-check
            # Probe開始までの秒数
            initialDelaySeconds: 30
            # Probeの間隔を秒単位で指定する。デフォルトは10秒で最小の値は1秒
            periodSeconds: 30
            # Probeがタイムアウトするまでの秒数。デフォルトは1秒で最小の値は1秒
            timeoutSeconds: 5
            # Probeが失敗したと判断する最小回数を指定。デフォルトは3回
            failureThreshold: 5
            #
            successThreshold: 1
