---
#--------------------------------------------------------------
# Service
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
