apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#--------------------------------------------------
# Change value
#--------------------------------------------------
namePrefix: base-
namespace: base-app
commonLabels:
  app: mysql
  env: production
  project: "test"
images:
  - name: mysql
    # newName: mysql
    newTag: "5.6"
#--------------------------------------------------
# Base
#--------------------------------------------------
bases:
  - ../../../../base/db/mysql
patchesStrategicMerge:
  - configmap.yaml