apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#--------------------------------------------------
# Change value
#--------------------------------------------------
namePrefix: base-
commonLabels:
  app: mysql
  env: local
images:
  - name: mysql
    # newName: mysql
    newTag: "5.6"
#--------------------------------------------------
# Base
#--------------------------------------------------
bases:
  - ../../../../base/local/db/mysql
patchesStrategicMerge:
  - patch-configmap.yaml
