---
#--------------------------------------------------------------
# Service
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  # svcという名前は含めること。DNSが引けなくなる。
  name: svc
spec:
  type: NodePort
  # type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30081
