---
#--------------------------------------------------------------
# Service
# https://kubernetes.io/ja/docs/concepts/services-networking/service/
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  # svcという名前は含めること。DNSが引けなくなる。
  name: svc
spec:
  type: NodePort
  # type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 80
      nodePort: 30082
