---
#--------------------------------------------------------------
# Secret for postgres
# https://kubernetes.io/docs/concepts/configuration/secret/
#--------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres
type: Opaque
data:
  # Default user is "admin".
  # echo -n 'admin' | base64
  postgres_user: YWRtaW4=
  # Default password is "rootpass".
  # echo -n 'rootpass' | base64
  postgres_password: cm9vdHBhc3M=
  # Default password is "rootpass".
  # echo -n 'rootpass' | base64
  pg_password: cm9vdHBhc3M=
