apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: nginx-
namespace: nginx-app
commonLabels:
  app: nginx
  env: production
  project: "test"
images:
  - name: image
    newName: nginx
    newTag: 1.17.9-alpine
bases:
  - ../../../base/nginx
patchesStrategicMerge:
  - service.yaml
resources:
  - namespace.yaml
