---
#--------------------------------------------------------------
# Service
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: service
# spec:
#   type: ClusterIP
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80
spec:
  type: ExternalName
  # {service}.{namespace}.svc.cluster.local
  externalName: nginx-service.nginx-app.svc.cluster.local
