---
#--------------------------------------------------------------
# Service
# https://kubernetes.io/ja/docs/concepts/services-networking/service/
#--------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
