---
#--------------------------------------------------------------
# StatefulSet
# https://kubernetes.io/ja/docs/concepts/workloads/controllers/statefulset/
#--------------------------------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  template:
    spec:
      # 削除されるまでの猶予の時間。デフォルトは30秒
      terminationGracePeriodSeconds: 60
      containers:
        - name: pod
          image: image:latest
          args: ["--requirepass", "test"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-volume
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      # ReadWriteOnce : 1つのNodeがPVをmountすることが出来る。読み書き可能。
      # ReadOnlyMany : 複数のNodeがPVをmountすることが出来る。読み取り専用。
      # ReadWriteMany : 複数のNodeがPVをmountすることが出来る。読み書き可能
      accessModes: "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
      storageClassName: redis-local-storage
