---
#--------------------------------------------------------------
# PersistentVolume for hostpath
# This is useful for single-node development and testing only! On-host storage is not supported in any way and WILL NOT WORK in a multi-node cluster.
# https://kubernetes.io/ja/docs/concepts/storage/persistent-volumes/
#--------------------------------------------------------------
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv
spec:
  storageClassName: local-storage-class
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data
