apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#--------------------------------------------------
# Change value
#--------------------------------------------------
commonLabels:
  app: argocd
  env: production
resources:
  - ingress.yaml
